[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "unixgeexen.computing"
authors = [{name = "unixgeexen", email = "unixgeexen@gmail.com"}]
dynamic = ["version", "description"]
